# Generated by Django 5.0.3 on 2025-04-08 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagePair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('image_fliter', models.FileField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='todoItem',
        ),
    ]
