# Generated by Django 5.0.3 on 2025-04-14 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_imagepair_delete_todoitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepair',
            name='image',
            field=models.FileField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='imagepair',
            name='image_fliter',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
