# Generated by Django 5.0.3 on 2025-04-14 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_imagepair_image_alter_imagepair_image_fliter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fliter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_fliter', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='Oringal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.DeleteModel(
            name='ImagePair',
        ),
    ]
